version: "3"

services:
  zama-client:
    image: zama-client-image
    container_name: zama-client-container
    build:
      context: ./zama-client # Adjust the path to your zama-client project
      dockerfile: Dockerfile
    # depends_on:
    #   - zama-server
    # command: ["upload", "--folder_path", "/app/data"] # Adjust the command to start your client with upload parameters
    environment:
      - SERVER_URL=http://zama-server:5000/v1/api
    # # command: ["./zama-client"] # Adjust the command to start your client
    networks:
      - zama_network
    # volumes:
    #   - ./zama-client-data:/app/data

  zama-server:
    image: zama-server-image
    container_name: zama-server-container
    build:
      context: ./zama-server
      dockerfile: Dockerfile
    # env_file:
    #   - ./zama-server/.env
    ports:
      - "5000:5000"
    command: ["./zama-server"]
    networks:
      - zama_network

networks:
  zama_network:
    name: zama_network
