version: "3"

services:
  zama-client:
    image: zama-client-image
    container_name: zama-client-container
    build:
      context: ./zama-client
      dockerfile: Dockerfile
    env_file:
      - ./zama-client/.env
    networks:
      - zama_network

  zama-server:
    image: zama-server-image
    container_name: zama-server-container
    build:
      context: ./zama-server
      dockerfile: Dockerfile
    env_file:
      - ./zama-server/.env
    ports:
      - "8080:8080"
    command: ["./zama-server"]
    networks:
      - zama_network

networks:
  zama_network:
    name: zama_network
